# Generated by Django 4.2.8 on 2024-05-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Goal',
            field=models.IntegerField(blank=True, null=True, verbose_name='목표'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='assets',
            field=models.IntegerField(blank=True, null=True, verbose_name='자산'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='생년월일'),
        ),
    ]
