# Generated by Django 4.2.8 on 2024-05-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositproducts',
            name='spcl_cnd',
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='etc_note',
            field=models.TextField(verbose_name='기타 메모'),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='fin_prdt_cd',
            field=models.TextField(unique=True, verbose_name='상품코드'),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='fin_prdt_nm',
            field=models.TextField(verbose_name='금융 상품명'),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='join_deny',
            field=models.IntegerField(verbose_name='가입 거절 여부'),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='join_member',
            field=models.TextField(verbose_name='가입 멤버'),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='join_way',
            field=models.TextField(verbose_name='가입 방법'),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='kor_co_nm',
            field=models.TextField(verbose_name='한국 회사명'),
        ),
    ]
