# Generated by Django 4.2.8 on 2024-05-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assests',
        ),
        migrations.AddField(
            model_name='user',
            name='assets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
