# Generated by Django 4.2.8 on 2024-05-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Goal',
            new_name='goal',
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
