# Generated by Django 4.2.8 on 2024-05-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
